#!/usr/bin/env bash

SCRIPT="$1"

[ -z "$SCRIPT" ] && {
	echo "Syntax: `basename $0` script_name [ arg1 [ arg2 [...] ]" >&2
	exit 1
}

MYPATH="`realpath "$0"`"
MYDIR="`dirname "$MYPATH"`"

EXECUTABLE="$MYDIR/scripts/$SCRIPT.sh"

[ ! -x "$EXECUTABLE" ] && EXECUTABLE="$MYDIR/scripts/$SCRIPT.php"

[ ! -x "$EXECUTABLE" ] && {
	echo " !! Script $SCRIPT (neither .sh nor .php) not found, exiting."
	exit 1
} >&2

shift
"$EXECUTABLE" "$@"

